# Generated by Django 5.2.7 on 2025-10-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=222)),
                ('p_dsc', models.TextField(max_length=222)),
                ('p_price', models.IntegerField(max_length=222)),
            ],
        ),
    ]
