# Generated by Django 5.2.7 on 2025-10-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_image',
            field=models.ImageField(default=1, upload_to='productphoto'),
            preserve_default=False,
        ),
    ]
