# Generated by Django 5.2.7 on 2025-10-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0002_products_p_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ctaegories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=222)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='p_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='e_app.ctaegories'),
            preserve_default=False,
        ),
    ]
