# Generated by Django 5.2.7 on 2025-10-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0003_ctaegories_products_p_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_color',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('black', 'black'), ('white', 'white')], default='black'),
        ),
        migrations.AddField(
            model_name='products',
            name='p_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S'),
        ),
    ]
