# Generated by Django 5.2.7 on 2025-10-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0004_products_p_color_products_p_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_dsc',
            field=models.TextField(),
        ),
    ]
