# Generated by Django 5.2.7 on 2025-10-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0005_alter_products_p_dsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_price',
            field=models.FloatField(max_length=222),
        ),
    ]
