# Generated by Django 5.2.7 on 2025-10-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0006_alter_products_p_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='huddies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_category', models.CharField(max_length=222)),
                ('p_image', models.ImageField(upload_to='productphoto')),
                ('p_name', models.CharField(max_length=222)),
                ('p_dsc', models.TextField()),
                ('p_price', models.FloatField(max_length=222)),
                ('p_color', models.CharField(choices=[('red', 'red'), ('green', 'green'), ('black', 'black'), ('white', 'white')], default='black')),
                ('p_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='p_category',
            field=models.CharField(max_length=222),
        ),
        migrations.DeleteModel(
            name='ctaegories',
        ),
    ]
