# Generated by Django 5.2.7 on 2025-10-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0007_huddies_alter_products_p_category_delete_ctaegories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='huddies',
            new_name='extra',
        ),
    ]
