# Generated by Django 5.2.7 on 2025-10-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0008_rename_huddies_extra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extra',
        ),
    ]
