# Generated by Django 5.2.7 on 2025-10-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0009_delete_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_price',
            field=models.CharField(max_length=222),
        ),
    ]
