# Generated by Django 5.2.7 on 2025-10-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0013_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Larg'), ('XL', 'XLarge'), ('XXL', 'extra large')], default='S'),
        ),
    ]
