# Generated by Django 5.2.7 on 2025-10-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0014_alter_products_p_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_size',
            field=models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('XLarge', 'XL'), ('extra large', 'XXL')], default='S'),
        ),
    ]
