# Generated by Django 5.2.7 on 2025-10-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0015_alter_products_p_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='p_color',
        ),
        migrations.RemoveField(
            model_name='products',
            name='p_size',
        ),
    ]
