# Generated by Django 5.2.7 on 2025-10-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0016_remove_products_p_color_remove_products_p_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('address', models.CharField(max_length=222)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
