# Generated by Django 5.2.7 on 2025-10-27 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0017_shoping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('address', models.CharField(max_length=222)),
                ('phone_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='shoping',
        ),
        migrations.AddField(
            model_name='products',
            name='p_title',
            field=models.CharField(default=1, max_length=222),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='p_category',
            field=models.CharField(choices=[('keyboard', 'keyboard'), ('graphic card', 'graphic card'), ('LED', 'LED')]),
        ),
    ]
