# Generated by Django 5.2.7 on 2025-10-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0018_orders_delete_shoping_products_p_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='p_name',
        ),
    ]
