# Generated by Django 5.2.7 on 2025-10-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0019_remove_products_p_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_name',
            field=models.CharField(default=1, max_length=222),
            preserve_default=False,
        ),
    ]
