# Generated by Django 3.2.12 on 2025-10-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0020_orders_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_category',
            field=models.CharField(choices=[('keyboard', 'keyboard'), ('graphic card', 'graphic card'), ('LED', 'LED')], max_length=12),
        ),
    ]
