# Generated by Django 3.2.12 on 2025-11-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0021_alter_products_p_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='p_image',
        ),
        migrations.CreateModel(
            name='productimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(upload_to='photo/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='e_app.products')),
            ],
        ),
    ]
