# Generated by Django 3.2.12 on 2025-11-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0022_auto_20251102_0703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
